using Volo.Abp.Identity;
using WalletApp3.PaymentTypeCategories;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using WalletApp3.Permissions;
using WalletApp3.BillDetails;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using WalletApp3.Shared;

namespace WalletApp3.BillDetails
{
    public class BillDetailsAppService : BillDetailsAppServiceBase, IBillDetailsAppService
    {
        //<suite-custom-code-autogenerated>
        public BillDetailsAppService(IBillDetailRepository billDetailRepository, BillDetailManager billDetailManager, IDistributedCache<BillDetailDownloadTokenCacheItem, string> downloadTokenCache, IRepository<WalletApp3.PaymentTypeCategories.PaymentTypeCategory, int> paymentTypeCategoryRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(billDetailRepository, billDetailManager, downloadTokenCache, paymentTypeCategoryRepository, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}