using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using WalletApp3.Permissions;
using WalletApp3.PaymentTypeCategories;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using WalletApp3.Shared;

namespace WalletApp3.PaymentTypeCategories
{
    public class PaymentTypeCategoriesAppService : PaymentTypeCategoriesAppServiceBase, IPaymentTypeCategoriesAppService
    {
        //<suite-custom-code-autogenerated>
        public PaymentTypeCategoriesAppService(IPaymentTypeCategoryRepository paymentTypeCategoryRepository, PaymentTypeCategoryManager paymentTypeCategoryManager, IDistributedCache<PaymentTypeCategoryDownloadTokenCacheItem, string> downloadTokenCache)
            : base(paymentTypeCategoryRepository, paymentTypeCategoryManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}