using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace WalletApp3.PaymentTypeCategories
{
    public class PaymentTypeCategory : PaymentTypeCategoryBase
    {
        //<suite-custom-code-autogenerated>
        protected PaymentTypeCategory()
        {

        }

        public PaymentTypeCategory(string categoryName, bool status, string description, DateTime lastModifiercationTime)
            : base(categoryName, status, description, lastModifiercationTime)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}